jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore practice2026/practice2025.slnx

    - name: Build project
      run: dotnet build practice2026/practice2025.slnx --no-restore --configuration Release

    - name: Run xUnit Tests
      run: dotnet test practice2026/practice2025.slnx --no-restore --configuration Release --verbosity normal
